import { Link } from 'react-router-dom'
import { usePageTitle } from '../usePageTitle'
import './About.css'

export default function About() {
  usePageTitle('About')
  return (
    <div className="page-wrap">
      <div className="page-hero">
        <h1>About Cream City Docket</h1>
        <p>Milwaukee government, made understandable.</p>
      </div>

      <div className="page-body">
        <div className="page-main">
          <p className="about-intro">
            Cream City Docket tracks Milwaukee Common Council legislation and sends plain-English
            alerts so residents can act before a vote happens, not after.
          </p>

          <section className="about-section">
            <h2>Why this exists</h2>
            <p>
              In April 2026, the Milwaukee Common Council passed a 10 PM food truck curfew downtown.
              The vote was unanimous. Most residents found out after it had already passed.
            </p>
            <p>
              That experience is common. Milwaukee's legislative data is technically public. It's all
              on the city's Legistar system, but it's fragmented, hard to navigate, and rarely covered
              by local media until after decisions are final. By the time most residents learn a bill
              exists, the window to testify, contact their alder, or influence the outcome has already closed.
            </p>
            <p>Cream City Docket exists to close that gap.</p>
          </section>

          <section className="about-section">
            <h2>How it works</h2>
            <ol className="about-steps">
              <li>The system checks Milwaukee's public Legistar API every hour for new and updated legislation.</li>
              <li>Each bill is summarized in plain English using Claude Haiku, an AI model from Anthropic.</li>
              <li>Bills are tagged by issue area from a fixed set of categories.</li>
              <li>Subscribers get email alerts when matching bills are introduced, scheduled for a hearing, or voted on.</li>
              <li>Every summary links directly back to the original filing on Legistar.</li>
            </ol>
          </section>

          <section className="about-section">
            <h2>A note on AI summaries</h2>
            <p>
              Summaries on this site are generated by an AI and are meant to help you understand
              what a bill does, not to replace the official text. If you are making any decision
              based on legislation, always read the source document on Legistar.
            </p>
            <p>
              You can turn off AI summaries in <Link to="/settings">Settings</Link> and see the
              official bill title instead.
            </p>
          </section>

          <section className="about-section">
            <h2>What this is not</h2>
            <ul className="about-not-list">
              <li>Not partisan or ideologically affiliated</li>
              <li>Not a replacement for journalism</li>
              <li>Not a data harvesting tool. Email addresses are only used to send alerts and are never shared.</li>
              <li>Not opinion presented as fact</li>
            </ul>
          </section>

          <section className="about-section">
            <h2>Data sources</h2>
            <ul className="about-sources">
              <li><strong>Legislative data</strong> from City of Milwaukee Legistar (public API)</li>
              <li><strong>AI summaries</strong> from Anthropic Claude Haiku</li>
              <li><strong>Alder contact info and photos</strong> from the City of Milwaukee Common Council website</li>
            </ul>
          </section>

          <section className="about-section">
            <h2>Built by</h2>
            <p>
              Kate Thompson, Software Engineering student at Milwaukee School of Engineering and Milwaukee resident.
            </p>
            <p className="about-contact">
              Questions or feedback: <a href="mailto:hello@creamcitydocket.com">hello@creamcitydocket.com</a>
            </p>
          </section>
        </div>

        <aside className="page-sidebar">
          <div className="glossary">
            <h3>Civic Glossary</h3>
            <dl>
              <dt>Ordinance</dt>
              <dd>A permanent change to Milwaukee's municipal code. Takes effect the day after publication.</dd>

              <dt>Charter Ordinance</dt>
              <dd>Changes the City Charter itself. Requires a 2/3 council vote (10 of 15 alders) and takes effect 60 days after publication.</dd>

              <dt>Resolution</dt>
              <dd>A one-time policy directive or formal statement. Does not permanently change city law.</dd>

              <dt>Committee Hearing</dt>
              <dd>Most bills go through a standing committee before a full council vote. Public testimony is accepted at committee hearings.</dd>

              <dt>Veto Override</dt>
              <dd>If the mayor vetoes a bill, the council can override it with 10 votes, which is 2/3 of the 15 alders.</dd>

              <dt>Substitute File</dt>
              <dd>When a bill is amended significantly, a new version called a substitute replaces the original text.</dd>

              <dt>Placed on File</dt>
              <dd>The bill is shelved without a final vote. It can be recalled later but is effectively on hold.</dd>
            </dl>
          </div>
        </aside>
      </div>
    </div>
  )
}
