import './About.css'

export default function About() {
  return (
    <div className="page-wrap">
      <div className="page-hero">
        <h1>About Cream City Docket</h1>
        <p>Milwaukee government, made understandable.</p>
      </div>

      <div className="page-body">
        <div className="page-main">
          <p className="about-intro">
            Cream City Docket is a civic transparency tool that monitors Milwaukee Common Council
            legislation and delivers plain-English summaries and timely alerts so residents can act
            before votes happen — not after.
          </p>

          <section className="about-section">
            <h2>Why this exists</h2>
            <p>
              In April 2026, the Milwaukee Common Council passed a 10 PM food truck curfew downtown.
              The vote was unanimous. Most residents found out after it had already passed.
            </p>
            <p>
              That experience is common. Milwaukee's legislative data is technically public — it's all
              on the city's Legistar system — but it's fragmented, hard to navigate, and rarely covered
              by media until after decisions are final. By the time most residents learn a bill exists,
              the window to testify, contact their alder, or influence the outcome has already closed.
            </p>
            <p>Cream City Docket exists to close that gap.</p>
          </section>

          <section className="about-section">
            <h2>How it works</h2>
            <ol className="about-steps">
              <li>The system checks Milwaukee's public Legistar API every hour for new and updated legislation.</li>
              <li>Each bill is summarized in plain English using Claude Haiku (Anthropic's AI).</li>
              <li>Bills are tagged by issue area from a fixed taxonomy.</li>
              <li>Subscribers receive email alerts when matching bills are introduced, scheduled, or voted on.</li>
              <li>All original source documents link directly back to official city records.</li>
            </ol>
          </section>

          <section className="about-section">
            <h2>On AI-generated summaries</h2>
            <p>
              Summaries on this site are generated by an AI (Claude Haiku by Anthropic) and are
              intended to help you understand what a bill does — not to replace the official text.
              Every summary links to the original filing on Legistar. If you are making a decision
              based on legislation, always read the source document.
            </p>
            <p>
              You can turn off AI summaries in <a href="/settings">Settings</a> and see official text instead.
            </p>
          </section>

          <section className="about-section">
            <h2>What this is not</h2>
            <ul className="about-not-list">
              <li>Not partisan or ideologically affiliated</li>
              <li>Not a replacement for journalism</li>
              <li>Not a data harvesting tool — email addresses are only used to send alerts</li>
              <li>Not opinion disguised as fact</li>
            </ul>
          </section>

          <section className="about-section">
            <h2>Data sources</h2>
            <ul className="about-sources">
              <li><strong>Legislative data</strong> — City of Milwaukee Legistar (public API)</li>
              <li><strong>AI summaries</strong> — Anthropic Claude Haiku</li>
              <li><strong>Alder contact info</strong> — City of Milwaukee Common Council website</li>
            </ul>
          </section>

          <section className="about-section">
            <h2>Built by</h2>
            <p>
              Kate Thompson · Software Engineering student, Milwaukee School of Engineering · Milwaukee resident
            </p>
            <p className="about-contact">
              Questions or feedback: <a href="mailto:hello@creamcitydocket.com">hello@creamcitydocket.com</a>
            </p>
          </section>
        </div>

        <aside className="page-sidebar">
          <div className="glossary">
            <h3>Civic Glossary</h3>
            <dl>
              <dt>Ordinance</dt>
              <dd>Permanent change to Milwaukee's municipal code. Takes effect the day after publication.</dd>

              <dt>Charter Ordinance</dt>
              <dd>Changes the City Charter itself. Requires a 2/3 council vote and takes effect 60 days after publication.</dd>

              <dt>Resolution</dt>
              <dd>A one-time policy directive or statement. Doesn't change permanent law.</dd>

              <dt>Committee Hearing</dt>
              <dd>Most bills are reviewed by a standing committee before going to the full council. Public testimony is accepted here.</dd>

              <dt>Veto Override</dt>
              <dd>If the mayor vetoes a bill, the council can override it with 10 votes (2/3 of 15 alders).</dd>

              <dt>Substitute File</dt>
              <dd>When a bill is amended significantly, a new version called a "substitute" replaces the original text.</dd>
            </dl>
          </div>
        </aside>
      </div>
    </div>
  )
}
