import { useState } from 'react'
import { useSettings } from '../useSettings'
import { usePageTitle } from '../usePageTitle'
import './Settings.css'

function Toggle({ label, sub, checked, onChange }: {
  label: string
  sub: string
  checked: boolean
  onChange: (v: boolean) => void
}) {
  return (
    <div className="toggle-row">
      <div className="toggle-text">
        <div className="toggle-label">{label}</div>
        <div className="toggle-sub">{sub}</div>
      </div>
      <button
        role="switch"
        aria-checked={checked}
        aria-label={label}
        className={`toggle-btn${checked ? ' toggle-btn--on' : ''}`}
        onClick={() => onChange(!checked)}
      >
        <span className="toggle-knob" />
      </button>
    </div>
  )
}

export default function Settings() {
  const { settings, update, reset } = useSettings()
  const [confirmReset, setConfirmReset] = useState(false)
  usePageTitle('Settings')

  return (
    <div className="page-wrap">
      <div className="page-hero">
        <h1>Settings</h1>
        <p>Site-wide display preferences. Saved in your browser, no account required.</p>
      </div>

      <div className="settings-body">
        <div className="settings-main">

          {/* AI & Summaries */}
          <section className="settings-section">
            <h2>AI &amp; Summaries</h2>
            <p className="settings-desc">
              Cream City Docket uses AI to generate plain-language summaries of legislation.
              These settings control how that content appears.
            </p>
            <Toggle
              label="Show AI-generated summaries"
              sub="Each bill shows a plain-English summary generated by Claude Haiku."
              checked={settings.showSummaries}
              onChange={v => update('showSummaries', v)}
            />
            {!settings.showSummaries && (
              <div className="settings-info">
                <strong>AI summaries off:</strong> Bills display the official title and file number only.
                Click any bill to read the full text on Legistar.
              </div>
            )}
            <Toggle
              label="Show AI confidence indicator"
              sub="Displays a note when a summary may be less reliable — e.g. very short or highly technical bill text."
              checked={settings.showConfidenceIndicator}
              onChange={v => update('showConfidenceIndicator', v)}
            />

          </section>

          {/* Accessibility */}
          <section className="settings-section">
            <h2>Accessibility</h2>
            <p className="settings-desc">Display preferences to improve readability and usability.</p>
            <Toggle
              label="High contrast mode"
              sub="Increases contrast between text and background."
              checked={settings.highContrast}
              onChange={v => update('highContrast', v)}
            />
            <Toggle
              label="Large text mode"
              sub="Increases base font size throughout the site."
              checked={settings.largeText}
              onChange={v => update('largeText', v)}
            />
            <Toggle
              label="Reduce motion"
              sub="Disables animations and transitions."
              checked={settings.reduceMotion}
              onChange={v => update('reduceMotion', v)}
            />
            <Toggle
              label="Dyslexia-friendly font"
              sub="Switches to Atkinson Hyperlegible, a typeface designed for improved readability."
              checked={settings.dyslexiaFont}
              onChange={v => update('dyslexiaFont', v)}
            />
          </section>

          {/* Display */}
          <section className="settings-section">
            <h2>Display</h2>
            <Toggle
              label="Show glossary tooltips"
              sub='Shows "?" icons next to civic and legal terms with plain-English explanations.'
              checked={settings.showTooltips}
              onChange={v => update('showTooltips', v)}
            />
            <Toggle
              label="Show file numbers"
              sub="Displays Legistar file numbers on bill cards in the feed."
              checked={settings.showFileNumbers}
              onChange={v => update('showFileNumbers', v)}
            />
            <Toggle
              label="Compact bill feed"
              sub="Hides summary text in the feed — more bills visible at once."
              checked={settings.compactFeed}
              onChange={v => update('compactFeed', v)}
            />
            <div className="toggle-row">
              <div className="toggle-text">
                <div className="toggle-label">Default bill type</div>
                <div className="toggle-sub">What type of legislation the feed shows when you first visit. You can always change it on the feed page.</div>
              </div>
              <select
                className="settings-select"
                value={settings.defaultTypeFilter}
                onChange={e => update('defaultTypeFilter', e.target.value)}
              >
                <option value="">Legislative matters only (default)</option>
                <option value="__all__">All types</option>
                <option value="Ordinance">Ordinances only</option>
                <option value="Resolution">Resolutions only</option>
                <option value="Charter Ordinance">Charter Ordinances only</option>
              </select>
            </div>
          </section>

          <div className="settings-reset">
            {confirmReset ? (
              <div className="reset-confirm">
                <span>Reset all settings to default?</span>
                <button className="reset-btn reset-btn--confirm" onClick={() => { reset(); setConfirmReset(false) }}>Yes, reset</button>
                <button className="reset-btn reset-btn--cancel" onClick={() => setConfirmReset(false)}>Cancel</button>
              </div>
            ) : (
              <button className="reset-btn" onClick={() => setConfirmReset(true)}>Reset all settings to default</button>
            )}
            <p>Settings are stored in your browser. Clearing browser data will reset them.</p>
          </div>
        </div>

        <aside className="settings-sidebar">
          <div className="sidebar-card">
            <h3>About these settings</h3>
            <p>All settings are saved locally in your browser using localStorage. No account required and nothing is sent to our servers.</p>
          </div>
          <div className="sidebar-card">
            <h3>Manage your alerts</h3>
            <p>To update your email alert preferences or unsubscribe, use the link in any alert email you've received.</p>
            <a href="/subscribe" className="sidebar-link">Set up alerts →</a>
          </div>
          <div className="sidebar-card">
            <h3>Accessibility resources</h3>
            <p>If you need assistance accessing content on this site, contact us at{' '}
              <a href="mailto:hello@creamcitydocket.com" className="sidebar-link" style={{ display: 'inline', marginTop: 0 }}>
                hello@creamcitydocket.com
              </a>
            </p>
          </div>
        </aside>
      </div>
    </div>
  )
}
