"""initial schema

Revision ID: 97263e2118bf
Revises: 
Create Date: 2026-04-30 16:48:30.998888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97263e2118bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legistar_person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legistar_person_id')
    )
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legistar_body_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legistar_body_id')
    )
    op.create_table('issue_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('matters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legistar_matter_id', sa.Integer(), nullable=False),
    sa.Column('legistar_guid', sa.String(length=36), nullable=False),
    sa.Column('file_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('matter_type', sa.String(length=100), nullable=False),
    sa.Column('matter_status', sa.String(length=100), nullable=False),
    sa.Column('body_name', sa.String(length=300), nullable=True),
    sa.Column('intro_date', sa.DateTime(), nullable=True),
    sa.Column('agenda_date', sa.DateTime(), nullable=True),
    sa.Column('passed_date', sa.DateTime(), nullable=True),
    sa.Column('enactment_date', sa.DateTime(), nullable=True),
    sa.Column('enactment_number', sa.String(length=50), nullable=True),
    sa.Column('current_text_id', sa.String(length=20), nullable=True),
    sa.Column('current_text_version', sa.String(length=10), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_utc', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legistar_matter_id')
    )
    op.create_table('poll_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polled_at', sa.DateTime(), nullable=False),
    sa.Column('matters_fetched', sa.Integer(), nullable=False),
    sa.Column('matters_upserted', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legistar_event_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('body_name', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legistar_event_id')
    )
    op.create_table('matter_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(length=200), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'action_name', 'action_date')
    )
    op.create_table('matter_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('alder_id', sa.Integer(), nullable=False),
    sa.Column('matter_version', sa.String(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alder_id'], ['alders.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'alder_id', 'matter_version')
    )
    op.create_table('matter_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['issue_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'tag_id')
    )
    op.create_table('mayor_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'action_type')
    )
    op.create_table('subscriber_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=20), nullable=False),
    sa.Column('preference_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'preference_type', 'preference_value')
    )
    op.create_table('event_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legistar_event_item_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=True),
    sa.Column('action_name', sa.String(length=200), nullable=True),
    sa.Column('passed_flag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legistar_event_item_id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legistar_vote_id', sa.Integer(), nullable=False),
    sa.Column('alder_id', sa.Integer(), nullable=False),
    sa.Column('event_item_id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=True),
    sa.Column('vote_value', sa.String(length=50), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alder_id'], ['alders.id'], ),
    sa.ForeignKeyConstraint(['event_item_id'], ['event_items.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alder_id', 'event_item_id'),
    sa.UniqueConstraint('legistar_vote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('event_items')
    op.drop_table('subscriber_preferences')
    op.drop_table('mayor_actions')
    op.drop_table('matter_tags')
    op.drop_table('matter_sponsors')
    op.drop_table('matter_history')
    op.drop_table('events')
    op.drop_table('alert_log')
    op.drop_table('subscribers')
    op.drop_table('poll_log')
    op.drop_table('matters')
    op.drop_table('issue_tags')
    op.drop_table('committees')
    op.drop_table('alders')
    # ### end Alembic commands ###
